name: dbt_analytics_demo
version: "1.0.0"
config-version: 2

profile: dbt_analytics_demo

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_analytics_demo:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
